apiVersion: batch/v1
kind: CronJob
metadata:
  name: registro-cronjob
  namespace: sa-p5
spec:
  schedule: "*/2 * * * *"  # Cada 2 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-registro
              image: angelsique/cron-registro:latest
              volumeMounts:
                - name: data-volume
                  mountPath: /registro
          volumes:
            - name: data-volume
              emptyDir: {}  # Temporal, se borra al reiniciar el pod
          restartPolicy: OnFailure
