version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurant_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  reservation-service:
    build: ./reservation-service
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    env_file:
      - ./reservation-service/.env

  payment-service:
    build: ./payment-service
    ports:
      - "5003:5003"
    depends_on:
      - mysql
    env_file:
      - ./payment-service/.env

  restaurant-info-service:
    build: ./restaurant-info-service
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    env_file:
      - ./restaurant-info-service/.env

  customer-auth-service:
    build: ./customer-auth-service
    ports:
      - "4001:4001"
    depends_on:
      - mysql
    env_file:
      - ./customer-auth-service/.env

volumes:
  mysql-data: