apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: sa-p5
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
