apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: p8-logs
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - name: http
      protocol: TCP
      port: 5004
      targetPort: 5004
