apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: sa-p5
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
