apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: p8-logs
  labels:
    app: users-service  
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - name: http 
      protocol: TCP
      port: 5001
      targetPort: 5001
