apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: p8-logs
  labels:
    app: chatbot
spec:
  type: ClusterIP
  selector:
    app: chatbot
  ports:
    - name: http
      protocol: TCP
      port: 5010
      targetPort: 5010
