apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: p8-logs
  labels:
    app: orders-service
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: http
      protocol: TCP
      port: 5003
      targetPort: 5003
