apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: p8-logs
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    rule_files:
      - /etc/prometheus/alerts.yml

    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: p8-logs
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+):(?:\d+);(.+)
            replacement: $1:$2
            target_label: __address__

      - job_name: 'users-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['users-service.p8-logs.svc.cluster.local:5001']

      - job_name: 'products-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['products-service.p8-logs.svc.cluster.local:5002']

      - job_name: 'orders-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['orders-service.p8-logs.svc.cluster.local:5003']

  alerts.yml: |
    groups:
      - name: general-alerts
        rules:
          - alert: ServiceDown
            expr: up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Servicio {{ $labels.job }} caído"
              description: "El servicio {{ $labels.job }} ({{ $labels.instance }}) no está respondiendo."

          - alert: HighLatencyProducts
            expr: rate(graphql_response_time_seconds_sum[1m]) / rate(graphql_response_time_seconds_count[1m]) > 1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Latencia elevada en products-service"
              description: "La latencia promedio de GraphQL en products-service excede 1s."

          - alert: HighHttpErrorsUsers
            expr: rate(users_http_errors_total[1m]) > 5
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Errores HTTP en users-service"
              description: "Más de 5 errores HTTP por segundo en users-service."
