apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: sa-p5
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
