apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: products-hpa
  namespace: p8-logs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
