apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-sysctl
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: elastic-sysctl
  template:
    metadata:
      labels:
        name: elastic-sysctl
    spec:
      hostPID: true
      containers:
        - name: sysctl
          image: busybox
          command: ["sh", "-c", "sysctl -w vm.max_map_count=262144 && sleep 3600"]
          securityContext:
            privileged: true
      restartPolicy: Always