apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
  namespace: p8-logs
  labels:
    app: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: angelsique/chatbot-service:v2.1
          ports:
            - containerPort: 5010
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api_key
            - name: PRODUCTOS_URL
              value: "http://products-service:5002/products/graphql"
            - name: ORDERS_URL
              value: "http://orders-service:5003/orders/graphql"
            - name: INVENTORY_URL
              value: "http://inventory-service:5004/inventory"
