apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  namespace: p8-logs
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5002"
    spec:
      containers:
        - name: products
          image: angelsique/products-service:latest
          ports:
            - containerPort: 5002
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
