apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  namespace: p8-logs
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: angelsique/orders-service:latest
          ports:
            - containerPort: 5003
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
