apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: sa-p5
spec:
  type: ClusterIP
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
